apiVersion: v1
kind: Pod
metadata:
  name: my-pod-name
  labels:
    app: my-app
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: my-env-password
        value: password
