apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: records-api-hpa
  labels:
    app: records-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: records-api-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50